### PR TITLE
Use fadvise(WILLNEED) to hint the caching

### PR DESCRIPTION
**Pull request by windkit**

### CODE REVIEW

**Comment by mocchira** [comment]
@windkit I have a little bit concern about this change might make leo_storage startup slower especially in case num_of_containers is set to very large number like @vstax use cases (total: 512 with 4 directories). so just in case, take the time to startup with

- 128 * 4 num_of_containers
- load as much files as possible beforehand 

then compare the one with PR and the other without PR to confirm there is negligible time difference.

**Comment by vstax** [comment]
@mocchira 
From what I understand this should have no relation to startup, it (as described on https://github.com/basho/leveldb/wiki/mv-fadvise-control) affects whether it's instructed to OS cache to try to keep all metadata in RAM or not (just for .sst files, as write logs are already in RAM) or not. Instead of some internal leveldb logic it will demand to keep all metadata in OS cache. So as I understand, this will show performance increase on fresh system with low amount of metadata and lots of RAM (e.g. during benchmark) but can kill performance on system where amount of metadata is much higher than RAM by eating all the cache for metadata and leaving not much for AVS operations. Hard to say, though, this all depends on type of load.

Consider this configuration:
```
[vm@stor04 mnt]$ du -sm avs?/bodies/metadata/
9334	avs1/bodies/metadata/
9332	avs2/bodies/metadata/
9332	avs3/bodies/metadata/
9334	avs4/bodies/metadata/
[vm@stor04 mnt]$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        7,0G        357M         40M         23G         23G
Swap:          4,0G         38M        4,0G
```
fadvise(WILLNEED) would demand that ~32 GB of .sst files are to be kept in cache on this system (total size is 37 GB but around 4.5GB of them are .log files), but there is just 23 GB of cache available anyway! I think this option should be configurable, it probably acts just like it's described in that document - enhances performance when metadata is much smaller than available cache size and gives doubtful results otherwise.

**Comment by mocchira** [comment]
@vstax Thanks for pointing this out.

> From what I understand this should have no relation to startup

From what I've checked the actual code base, Yes no relation at all. I misunderstood prefetch can happen on opening files.

> fadvise(WILLNEED) would demand that ~32 GB of .sst files are to be kept in cache on this system (total size is 37 GB but around 4.5GB of them are .log files), but there is just 23 GB of cache available anyway! I think this option should be configurable, it probably acts just like it's described in that document - enhances performance when metadata is much smaller than available cache size and gives doubtful results otherwise.

Yes WILLNEED should be configurable.
@windkit Can you take that into account on this PR?

**Comment by windkit** [comment]
@mocchira I have updated the PR to make the option configurable

**Comment by mocchira** [comment]
LGTM. Thanks.

**Pull request merged**
